apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-service1
  labels:
    app: services-service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: services-service1
  template:
    metadata:
      labels:
        app: services-service1
    spec:
      containers:
      - name: services-service1
        image: simret101/services_service1:latest
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: services-service1
spec:
  selector:
    app: services-service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
